### ISSUE TITLE
Crash after migration to 2.2

### ISSUE THREAD

**Issue by stepango** [nitrico/LastAdapter#20]
Can't make LastAdapter work on complex lists after migration to 2.2
So far I rollback all changes and keep using 2.0
```
05-02 17:58:39.019 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.ninetyseconds.auckland.debug, PID: 7837
                                     kotlin.KotlinNullPointerException
                                         at com.github.nitrico.lastadapter.LastAdapter$onCreateViewHolder$1.onPreBind(LastAdapter.kt:94)
                                         at android.databinding.ViewDataBinding$4.onNotifyCallback(ViewDataBinding.java:118)
                                         at android.databinding.ViewDataBinding$4.onNotifyCallback(ViewDataBinding.java:112)
                                         at android.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:201)
                                         at android.databinding.CallbackRegistry.notifyFirst64(CallbackRegistry.java:122)
                                         at android.databinding.CallbackRegistry.notifyRemainder(CallbackRegistry.java:169)
                                         at android.databinding.CallbackRegistry.notifyRecurse(CallbackRegistry.java:145)
                                         at android.databinding.CallbackRegistry.notifyCallbacks(CallbackRegistry.java:91)
                                         at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:371)
                                         at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
                                         at com.github.nitrico.lastadapter.LastAdapter.onBindViewHolder(LastAdapter.kt:108)
                                         at com.github.nitrico.lastadapter.LastAdapter.onBindViewHolder(LastAdapter.kt:27)
                                         at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                         at com.github.nitrico.lastadapter.LastAdapter.onBindViewHolder(LastAdapter.kt:122)
                                         at com.github.nitrico.lastadapter.LastAdapter.onBindViewHolder(LastAdapter.kt:27)
                                         at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                         at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                         at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                         at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
05-02 17:58:39.019 E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
                                         at android.view.View.layout(View.java:17637)
                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                         at android.os.Handler.handleCallback(Handler.java:751)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)```

**Comment by nitrico** [comment]
Hi @stepango! Thanks for reporting the problem.

Can you please try again with version 2.2.2?

**Comment by stepango** [comment]
Works good so far, thanks a lot!

**Comment by nitrico** [comment]
Great :)
