### ISSUE TITLE
Crash after migration to 2.2.2

### ISSUE THREAD

**Issue by stepango** [nitrico/LastAdapter#22]
LastAdapter 2.2.2
Kotlin 1.1.2-3
Start experienced one more crash today with following stacktrace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3610)
                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
                                         at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1637)
                                         at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                         at android.view.Choreographer.doFrame(Choreographer.java:618)
                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                         at android.os.Handler.handleCallback(Handler.java:751)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by nitrico** [comment]
Hi @stepango, can you please check if the crash is fixed in version 2.3.0? Thanks

**Comment by amonkhepri** [comment]
Still doesn't work in 2.3.0
